version: '3'
services:
        amber:
                build: ./amber
                ports:
                        - "3030:3030"
                links:
                        - mongo
                environment:
                        - APP_NAME=${APP_NAME}
                        - APP_URL=${AMBER_URL}
                        - APP_SECRET_KEY=${APP_SECRET_KEY}
                        - APP_SECRET_IV=${APP_SECRET_IV}
                        - ENCRYPT_DATA=true
                        - CLIENT_URLS=${AMBER_STUDIO_URL},${AMBER_COLLECT_URL},${AMBER_VISIT_URL}
                        - MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PWD}@mongo:27017/amber?authSource=admin
                        - ADMINISTRATOR_EMAIL=${ADMINISTRATOR_EMAIL}
                        - ADMINISTRATOR_PWD=${ADMINISTRATOR_PWD}
                        - AMBER_STUDIO_URL=${AMBER_STUDIO_URL}
                        - AMBER_COLLECT_URL=${AMBER_COLLECT_URL}
                        - AMBER_VISIT_URL=${AMBER_VISIT_URL}
                        - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
                        - SENDINBLUE_API_KEY=${SENDINBLUE_API_KEY}
                        - FROM_EMAIL=${FROM_EMAIL}
        amber-studio:
                build:
                        context: ./amber-studio
                        args:
                                - AMBER_URL=${AMBER_URL}
                                - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
                ports:
                        - "3080:80"
        amber-collect:
                build:
                        context: ./amber-collect
                        args:
                                - AMBER_URL=${AMBER_URL}
                                - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
                ports:
                        - "3090:80"
        amber-visit:
                build:
                        context: ./amber-visit
                        args:
                                - AMBER_URL=${AMBER_URL}
                                - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
                ports:
                        - "3070:80"
        mongo:
                image: mongo
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
                        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
